#!/bin/bash
source="./test/dump/1"
dest="./test/dump/rdf"
# Define a timestamp function
timestamp() {
  date +"%d%m%y_%H-%M-%S"
}
for f in "$source"/*.json; do
  filename=$(basename "$f")
  extension="${filename##*.}"
  filename="${filename%.*}"
  if [ ! -e "$dest/$filename.ttl" ]; then
      if [[ $filename == *"_adm0"* ]]
        then
          level=0
        fi
      if [[ $filename == *"_adm1"* ]]
        then
          level=1
        fi
      if [[ $filename == *"_adm2"* ]]
        then
          level=2
        fi
      if [[ $filename == *"_adm3"* ]]
        then
          level=3
        fi
      if [[ $filename == *"_adm4"* ]]
        then
          level=4
        fi
      if [[ $filename == *"_adm5"* ]]
        then
          level=5
        fi
    echo " coverting \"$f\" to RDF...";
    ./geojson-rdf "$level" "$f" > "$dest/$filename.ttl";
    echo " done... RDF available at $dest/$filename.ttl";
  fi
done
